// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/login/[provider].ts";
import * as $1 from "./routes/api/logout.ts";
import * as $2 from "./routes/app/_middleware.tsx";
import * as $3 from "./routes/app/child/[childKey].tsx";
import * as $4 from "./routes/app/child/new.tsx";
import * as $5 from "./routes/app/index.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/signup.tsx";
import * as $$0 from "./islands/Avatar.tsx";
import * as $$1 from "./islands/SignIn.tsx";

const manifest = {
  routes: {
    "./routes/api/login/[provider].ts": $0,
    "./routes/api/logout.ts": $1,
    "./routes/app/_middleware.tsx": $2,
    "./routes/app/child/[childKey].tsx": $3,
    "./routes/app/child/new.tsx": $4,
    "./routes/app/index.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/signup.tsx": $7,
  },
  islands: {
    "./islands/Avatar.tsx": $$0,
    "./islands/SignIn.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
